"""This module defines the abstract base class for sampler plugins."""

from __future__ import annotations

from abc import abstractmethod
from typing import TYPE_CHECKING

from ropt.plugins.base import Plugin

if TYPE_CHECKING:
    from ropt.config import SamplerConfig
    from ropt.sampler import Sampler


class SamplerPlugin(Plugin):
    """Abstract Base Class for Sampler Plugins (Factories).

    This class defines the interface for plugins responsible for creating
    [`Sampler`][ropt.sampler.Sampler] instances. These plugins act as factories
    for specific sampling algorithms or strategies.
    """

    @classmethod
    @abstractmethod
    def create(
        cls,
        sampler_config: SamplerConfig,
    ) -> Sampler:
        """Factory method to create a concrete Sampler instance.

        This abstract class method serves as a factory for creating concrete
        [`Sampler`][ropt.sampler.Sampler] objects. Plugin implementations must
        override this method to return an instance of their specific `Sampler`
        subclass.

        The [`PluginManager`][ropt.plugins.manager.PluginManager] calls this
        method when an optimization requires samples generated by this plugin.

        Args:
            sampler_config:  The sampler configuration object.

        Returns:
            An initialized Sampler object ready for use.
        """
