"""This module defines the abstract base class for sampler plugins."""

from __future__ import annotations

from abc import abstractmethod
from typing import TYPE_CHECKING

from ropt.plugins.base import Plugin

if TYPE_CHECKING:
    from ropt.config import SamplerConfig
    from ropt.sampler import Sampler


class SamplerPlugin(Plugin):
    """Abstract base class for sampler plugins (factories).

    Creates [`Sampler`][ropt.sampler.Sampler] instances; concrete plugins
    implement `create` as a factory for their own `Sampler` subclass.
    """

    @classmethod
    @abstractmethod
    def create(
        cls,
        sampler_config: SamplerConfig,
    ) -> Sampler:
        """Create a Sampler instance.

        Called by the [`PluginManager`][ropt.plugins.manager.PluginManager]
        when an optimization requires samples generated by this plugin.

        Args:
            sampler_config:  The sampler configuration object.

        Returns:
            An initialized Sampler object ready for use.
        """
