"""This module defines the abstract base class for sampler plugins."""

from __future__ import annotations

from abc import abstractmethod
from typing import TYPE_CHECKING

from ropt.plugins.base import Plugin

if TYPE_CHECKING:
    import numpy as np
    from numpy.random import Generator
    from numpy.typing import NDArray

    from ropt.config import EnOptConfig
    from ropt.sampler import Sampler


class SamplerPlugin(Plugin):
    """Abstract Base Class for Sampler Plugins (Factories).

    This class defines the interface for plugins responsible for creating
    [`Sampler`][ropt.sampler.Sampler] instances. These plugins act as factories
    for specific sampling algorithms or strategies.
    """

    @classmethod
    @abstractmethod
    def create(
        cls,
        enopt_config: EnOptConfig,
        sampler_index: int,
        mask: NDArray[np.bool_] | None,
        rng: Generator,
    ) -> Sampler:
        """Factory method to create a concrete Sampler instance.

        This abstract class method serves as a factory for creating concrete
        [`Sampler`][ropt.sampler.Sampler] objects. Plugin implementations must
        override this method to return an instance of their specific `Sampler`
        subclass.

        The [`PluginManager`][ropt.plugins.manager.PluginManager] calls this
        method when an optimization requires samples generated by this plugin.
        Instances of `Sampler` subclasses are initialized with an
        [`EnOptConfig`][ropt.config.EnOptConfig] object detailing the
        optimization setup, the `sampler_index` identifying the specific sampler
        configuration to use from the config, an optional variable `mask`
        indicating which variables this sampler instance handles, and a NumPy
        random number generator (`rng`) for stochastic methods.

        Args:
            enopt_config:  The main EnOpt configuration object.
            sampler_index: Index into `enopt_config.samplers` for this sampler.
            mask:          Optional boolean mask for variable subset sampling.
            rng:           NumPy random number generator instance.

        Returns:
            An initialized Sampler object ready for use.
        """
