"""Plugin support for samplers.

A sampler generates the perturbed variable vectors that are used to estimate
stochastic gradients. A [`SamplerPlugin`][ropt.plugins.sampler.SamplerPlugin] is
a factory that creates the [`Sampler`][ropt.sampler.Sampler] objects doing the
actual work, which the [`PluginManager`][ropt.plugins.manager.PluginManager]
discovers through the `ropt.plugins.sampler` entry point group.

`ropt` ships [`SciPySampler`][ropt.sampler.scipy.SciPySampler], which is based
on the `scipy.stats` and `scipy.stats.qmc` packages.

See [Writing a Plugin](../utilities/writing_plugins.md) for a walkthrough.
"""

from __future__ import annotations

from abc import abstractmethod
from typing import TYPE_CHECKING

from ropt.plugins.base import Plugin

if TYPE_CHECKING:
    from ropt.config import SamplerConfig
    from ropt.sampler import Sampler


class SamplerPlugin(Plugin):
    """Abstract base class for sampler plugins (factories).

    Creates [`Sampler`][ropt.sampler.Sampler] instances; concrete plugins
    implement `create` as a factory for their own `Sampler` subclass.
    """

    @classmethod
    @abstractmethod
    def create(
        cls,
        sampler_config: SamplerConfig,
    ) -> Sampler:
        """Create a Sampler instance.

        Called by the [`PluginManager`][ropt.plugins.manager.PluginManager]
        when an optimization requires samples generated by this plugin.

        Args:
            sampler_config:  The sampler configuration object.

        Returns:
            An initialized Sampler object ready for use.
        """
